### ISSUE TITLE
Support for ASP.NET Core 5 & Versioned API Explorer

### ISSUE THREAD

**Issue by gingters** [microsoft/aspnet-api-versioning#662]
Hello,

are there plans to make the Api versioning compatible with .NET 5?

The current ASP.NET Core 5 web api templates include swagger, which in turn needs the versioned API explorer, but that package won't install in a .NET 5 RC1 web api project.

**Comment by commonsensesoftware** [comment]
Plans - yes, but there's nothing coming anytime _"soon"_. I run this project largely alone and I don't have capacity to chase pre-releases. I've been particularly booked up these past months. I'm currently working on burning down the existing set of issues. Once have got that down to a reasonable size, I'll start looking at support for .NET 5.0. The ASP.NET team usually reaches out if they expect to have visible breaking changes (but not always). I suspect the main work will be just adding an additional build target. I don't know what the exact planned date for .NET 5.0 is yet, but I know it will be in November.

Thanks for patience.

**Comment by gingters** [comment]
For your info:

I did a very quick check (replaced target framework netcoreapp3.1 by net5.0), hotpatched the compilation errors that resulted from the nullable types (if x == null throw...) and checked the swagger sample.

Result was: It worked with all version documents as I would expect that.

So, aside from the nullable type issues that should be resolved properly and not just shortcutted as I did for the very brief test it is indeed adding the target framework for net5.0 in addition to netcoreapp3.1 and that should be it.

**Comment by commonsensesoftware** [comment]
That's good to know. I've finally caught up with the backlog and I've knocked down the pile of OData issues. I'll start taking a look at this. There's about a month left before RTW, so there's a reasonable chance I'll have this ready by then. I'll almost certainly have to multi-target to support those not ready to push forward to .NET 5.0 just yet. That _should_ be the only level of complexity to deal with.

I also noticed that the ASP.NET team is planning on releasing in-box scaffolding for OpenAPI/Swagger with Swashbuckle. I may have to reach out and see if they are also interested in any versioning scaffolding as well. :)

I'll report back when I have package version ready.

**Comment by commonsensesoftware** [comment]
[5.0.0-preview.1](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/5.0.0-preview.1) is now available. I expect the official packages to land within a day of .NET 5.0. I don't currently have any other planned changes to the core libraries. I'm hope to have release parity with OData, but I won't let that hold this up. Thanks.

**Comment by PMExtra** [comment]
I'm looking forward for this.
.NET 5.0 stable is released several weeks. I need `ControllerNameAttribute` and `ActionNameAttribute` but `Microsoft.AspNetCore.Mvc.Versioning` still does not support .NET 5.0 .

**Comment by WeihanLi** [comment]
Is there a plan for 5.0 release date?

**Comment by PMExtra** [comment]
I think it's really compatible with .NET 5.0, it's only incompatible with .NET Standard 2.1

**Comment by kimsey0** [comment]
@commonsensesoftware: This can be closed, right?

**Comment by commonsensesoftware** [comment]
@kimsey0 yes, it can.

**Comment by kimsey0** [comment]
(I don't have permission to do it. I assumed you had. 🙂)

**Comment by commonsensesoftware** [comment]
The package released a while ago. Cleaning up issues. Thanks everyone.
